# Generated by Django 5.0.3 on 2024-03-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuptarget',
            name='client_last_contact',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='backuptarget',
            name='client_version',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
