# Generated by Django 5.0.3 on 2024-03-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_alter_backuptarget_client_last_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuptarget',
            name='client_last_contact',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
