# Generated by Django 5.0.3 on 2024-03-29 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0004_backuptarget_client_error_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.backuptarget')),
            ],
        ),
        migrations.CreateModel(
            name='BackupFileJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2048)),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.backupjob')),
            ],
        ),
    ]
