# Generated by Django 5.0.3 on 2024-03-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0006_rename_backupfilejobs_backupfilejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='run_cron',
            field=models.CharField(default='*.*.*.*', max_length=128),
            preserve_default=False,
        ),
    ]
