# Generated by Django 5.0.3 on 2024-03-31 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0008_backupjob_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_name', models.CharField(max_length=2048)),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.backupjob')),
            ],
        ),
    ]
