# Generated by Django 5.0.3 on 2024-03-31 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0009_backupcontainer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BackupContainer',
            new_name='BackupContainerVolume',
        ),
    ]
