# Generated by Django 5.0.3 on 2024-03-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0010_rename_backupcontainer_backupcontainervolume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupContainerVolume',
        ),
    ]
