# Generated by Django 5.0.3 on 2024-03-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0011_delete_backupcontainervolume'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupfilejob',
            name='name',
            field=models.CharField(default='Home Directory', max_length=2048),
            preserve_default=False,
        ),
    ]
