# Generated by Django 5.0.3 on 2024-04-07 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0012_backupfilejob_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupfilejob',
            name='path',
        ),
        migrations.CreateModel(
            name='BackupFileJobPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2048)),
                ('backup_file_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.backupfilejob')),
            ],
        ),
    ]
