# Generated by Django 5.0.3 on 2024-05-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0013_remove_backupfilejob_path_backupfilejobpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupfilejobpath',
            name='fs_type',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backupfilejobpath',
            name='stat_changed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backupfilejobpath',
            name='stat_modify',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backupfilejobpath',
            name='stat_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
