# Generated by Django 5.0.3 on 2024-05-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0014_backupfilejobpath_fs_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backupfilejobpath',
            old_name='stat_modify',
            new_name='stat_modified',
        ),
    ]
